// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_content_delivery_bucket": "shacklebolt-20180917143028--hostingbucket",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://d3czsyusemefrj.cloudfront.net",
    "aws_cognito_identity_pool_id": "us-east-1:5650b8c4-abd0-4e37-9cb5-3f27ae89bcb4",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_FfH14h8MR",
    "aws_user_pools_web_client_id": "5ino0lvom8t90lf69tn5iiqmmn",
    "aws_user_files_s3_bucket": "shacklebolt-storage",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
